
package br.com.caelum.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CalculadorDeParcela", targetNamespace = "http://webservices.caelum.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculadorDeParcela {


    /**
     * 
     * @param quantidade
     * @param valorTotal
     * @return
     *     returns double
     */
    @WebMethod(operationName = "CalculaParcela")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CalculaParcela", targetNamespace = "http://webservices.caelum.com.br/", className = "br.com.caelum.cliente.CalculaParcela")
    @ResponseWrapper(localName = "CalculaParcelaResponse", targetNamespace = "http://webservices.caelum.com.br/", className = "br.com.caelum.cliente.CalculaParcelaResponse")
    public double calculaParcela(
        @WebParam(name = "valorTotal", targetNamespace = "")
        double valorTotal,
        @WebParam(name = "quantidade", targetNamespace = "")
        int quantidade);

}
